theme: jekyll-theme-architect
title: srnyx's Templates
show_downloads: true
github:
  zip_url: https://github.com/srnyx/mc-server-templates/archive/refs/heads/main.zip
  tar_url: https://github.com/srnyx/mc-server-templates/archive/refs/heads/main.tar.gz
